# typed: true
# frozen_string_literal: true

# This file was generated by Homebrew Releaser. DO NOT EDIT.
class Huba < Formula
  desc "Tool for managing claude code tasks across all your projects without leaving t"
  homepage "https://github.com/sergeyzwezdin/huba"
  url "https://github.com/sergeyzwezdin/huba/archive/refs/tags/0.0.6.tar.gz"
  sha256 "f897087129cacfa468f657723f1ff1113e4877981f6bd3be4049c046ee97c186"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/sergeyzwezdin/huba/releases/download/0.0.6/huba-0.0.6-darwin-amd64.tar.gz"
      sha256 "ebbf9b8ac1c18754c0b9e079a726e80961d39689807923f656fa9fa79796312b"
    end

    on_arm do
      url "https://github.com/sergeyzwezdin/huba/releases/download/0.0.6/huba-0.0.6-darwin-arm64.tar.gz"
      sha256 "38031b35027917e957e561da199c0d9f72e4ab86abbabbdb53d667e113e9b71b"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/sergeyzwezdin/huba/releases/download/0.0.6/huba-0.0.6-linux-amd64.tar.gz"
      sha256 "1676424bd882d89d430c2f5fc307ba23e52ea98f1160b7753a4d0f765232a249"
    end

    on_arm do
      url "https://github.com/sergeyzwezdin/huba/releases/download/0.0.6/huba-0.0.6-linux-arm64.tar.gz"
      sha256 "116e47919e97860524efd04c54e9942ea93ca03e4c953ccb30f680f85c460be8"
    end
  end

  def install
    bin.install "hb"
  end

  test do
    assert_predicate bin/"hb", :exist?
  end
end
